apiVersion: v1
kind: Service
metadata:
  name: pyhttp
  labels:
    group: ProdGroup
spec:
  type: LoadBalancer
  selector:
    app: pyhttp
  ports:
    - protocol: TCP
      port: 7000
      targetPort: 7000
